### ISSUE TITLE
Rewrite and use a lisp-style syntax

### ISSUE THREAD

**Issue by bwbw223** [bwbw223/stache-lang#1]
As per title

**Comment by liam4** [comment]
Closed?

**Comment by bwbw223** [comment]
Reopened.  What do you think?  The change would probably simplify parsing.

**Comment by bwbw223** [comment]
Hmm I guess this must wait until next week...  I am stuck on a mobile client that doesn't support branch-creation...

**Comment by bwbw223** [comment]
Nvm...  The grammar is a bit ugly at the moment but I will clean it up when I have access to a computer.

**Comment by bwbw223** [comment]
Maybe I should not use nearley at all because s-exp parsers are easy enough to build without a parser library
